# A color code between 0-9 or a-f. Set to 'none' to disable.
# In 1.16+ you can use hex color codes here as well. (For example, #613e1d is brown).
ops-name-color: '4'

# The character(s) to prefix all nicknames, so that you know they are not true usernames.
# Users with essentials.nick.hideprefix will not be prefixed with the character(s)
nickname-prefix: '~'

# The maximum length allowed in nicknames. The nickname prefix is not included in this.
max-nick-length: 15

# The regex pattern used to determine if a requested nickname should be allowed for use.
# If the a requested nickname does not matched this pattern, the nickname will be rejected.
# Users with essentials.nick.allowunsafe will be able to bypass this check.
allowed-nicks-regex: '^[a-zA-Z_0-9ยง]+$'

# A list of phrases that cannot be used in nicknames. You can include regular expressions here.
# Users with essentials.nick.blacklist.bypass will be able to bypass this filter.
nick-blacklist:
#- Notch
#- 'MohamadRZ'

commands:
  - "nick"
  - "realname"
  - "size"
  - "gmv"
  - "gms"
  - "gmc"
  - "gma"

# When this option is enabled, nickname length checking will exclude color codes in player names.
# ie: "&6Notch" has 7 characters (2 are part of a color code), a length of 5 is used when this option is set to true
ignore-colors-in-max-nick-length: false

# Enables or disables the player size system entirely.
# If disabled, all related commands and features will be inactive.
size:
  # The minimum and maximum allowed player size.
  # Use -1 to disable the limit (no size restrictions).
  min: 0.1
  max: 100

  # The default size players will have when they join or reset.
  # If a player's size is reset, this value will be applied.
  default: 100

  # Cooldown time (in seconds) between each size change.
  # Use -1 to disable the cooldown system.
  cooldown: 10

  # List of allowed worlds where size changing is permitted.
  # If empty or not specified, size changing is allowed in all worlds.
  allowed-worlds:
    - world        # The "world" world allows size changes.
    - lobby        # The "lobby" world allows size changes.

  # List of blacklisted worlds where size changing is not allowed.
  # If empty or not specified, no worlds are blacklisted.
  blacklisted-worlds:
  # example
  #  - world_nether  # The "world_nether" world disallows size changes.
  #  - world_the_end # The "world_the_end" world disallows size changes.