<?php

namespace MohamadRZ\EssentialsZ;

use MohamadRZ\EssentialsZ\settings\Settings;
use MohamadRZ\EssentialsZ\user\OnlineUserCache;
use MohamadRZ\EssentialsZ\user\UserManager;
use pocketmine\plugin\PluginBase;

class EssentialsZPlugin extends PluginBase
{

    private static EssentialsZPlugin $instance;
    private UserManager $userManager;
    private Settings $settings;

    protected function onLoad(): void
    {
        self::$instance = $this;
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        $this->userManager = new UserManager($this);
        $this->settings = new Settings();
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public static function getInstance(): EssentialsZPlugin
    {
        return self::getInstance();
    }

    public function getUserManager(): UserManager
    {
        return $this->userManager;
    }

    public function getSettings(): Settings
    {
        return $this->settings;
    }
}